name: aEconomy
main: AlexBrin\aEconomy
version: 1.0
api: ['3.0.0', '3.0.0-ALPHA1', '3.0.0-ALPHA2', '3.0.0-ALPHA3', '3.0.0-ALPHA4', '3.0.0-ALPHA5', '3.0.0-ALPHA6']
author: AlexBrin

permissions:
  aeconomy:
    default: true
    children:
      aeconomy.admin:
        default: op
      aeconomy.use:
        default: true